### PR TITLE
Multi platform

### PR DESCRIPTION
**Pull request by ariehcore**
* Fixes case sensitivity so it will run on linux/mac
* adds setting theme toggle button

### CODE REVIEW

**Comment by MonbanZ** [comment]
these actually good addition if you dont mind to PR it to main branch.
we had plan to create in-app setting to give user more control on configuration like theme etc.
i believe @dy-dk is fine too for PR these changes

**Comment by ariehcore** [comment]
Ah really? Let me make the branch a little more in-line with base repo since I also changed a few other things and was doing things on the branch that I normally do when I start working on a project

**Comment by ariehcore** [comment]
@MonbanZ I tested it on Linux without building the program fully (used a `venv`), though I'm fairly new to Python so I have no idea how `pyinstaller` works for building executable versions of this

**Comment by ariehcore** [comment]
@MonbanZ should be all good for squash/merge into main branch :)

**Pull request merged**
